### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Crypt-iQ** [nguyenduyhieukma/CTF-Writeups#1]
Hi, I think here (https://github.com/nguyenduyhieukma/CTF-Writeups/tree/master/Google%20CTF%20Quals/2018/Crypto-DOGESTORE#odd-indexed-bytes) you mean

`a XOR 2^i + b XOR 2^i == a + b` instead of `a XOR b`

Great writeup though!

**Comment by nguyenduyhieukma** [comment]
I'm very happy that you have read, understand my idea and reported the typo. Thank you very much!
