### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by cothan** [nguyenduyhieukma/CTF-Writeups#2]
Link này die rồi, vì anh không để title nên người xem thấy link die sẽ không biết tìm đâu cả. 

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.182.9999&rep=rep1&type=pdf

Repo rất chất lượng. :heart:  no :rainbow:

**Comment by nguyenduyhieukma** [comment]
Thanks cothan đã report. Tạm thời mình đã update link mới, chắc ít bữa sẽ update thêm tiêu đề và review sơ sơ cho mỗi sách/khóa học.
